version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/latest/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose